# Installing and Importing PyTorch

**installing:**  
1. Check your GPU and CUDA Version
   * **nvidia-smi**
1. Run the Installation Command
   * from pip = **pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128**
   * from conda = **conda install pytorch torchvision torchaudio pytorch-cuda=12.8 -c pytorch -c nvidia**

**note.**(_pytorch-cuda=12.8 and cu128 are changeable according to the cuda version the device have_)

## Importing torch

In [1]:
import torch
print(torch.__version__)

2.9.1+cu128


In [2]:
print(f"Is CUDA available? {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Current device: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Capability: {torch.cuda.get_device_capability(0)}")
    print(f"PyTorch Version: {torch.__version__}")

Is CUDA available? True
Current device: NVIDIA GeForce GTX 1650
CUDA Capability: (7, 5)
PyTorch Version: 2.9.1+cu128


# Creating a Tensor

### using empty

In [37]:
"""
torch.empty(dim1, dim2)
it create space in the memory according to the given shape
return-type:torch.Tensor
"""
torch.empty(2,3)

tensor([[2.7511e-23, 1.9100e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

### using zeros

In [4]:
"""
torch.zeros(dim1, dim2)
creates a tensor of given shape and asign "0" to it 
"""
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### using ones

In [5]:
"""
torch.ones(dim1, dim2)
creates a tensor of given shape and asign "1" to it 
"""
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### using rand

In [6]:
"""
torch.rand(dim1, dim2)
creates a tensor of given shape and asign random values between(0-1) to it 
"""
torch.rand(2,3)

tensor([[0.2089, 0.6703, 0.9579],
        [0.9383, 0.7084, 0.6219]])

### manual_seed

In [7]:
"""
torch.manual_seed(seed_no)
insure that values are same every time for reuseability

torch.rand(dim1, dim2)
creates a tensor of given shape and asign random values between(0-1) to it 
"""
torch.manual_seed(45)
torch.rand(2,3)

tensor([[0.1869, 0.9613, 0.6834],
        [0.8988, 0.0505, 0.5555]])

### using tensor

In [8]:
'''
torch.tensor(python iterable)
create tensor for the given values of python-iterable
'''
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

### using arange

In [9]:
'''
torch.arange(start, stop, steps)
create a tensor according to the range
'''
torch.arange(0,20,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### using linespace

In [10]:
'''
torch.linspace(start, stop, number_of_values)
create a tensor of evenly space values between start and stop
'''
torch.linspace(2,15,3)

tensor([ 2.0000,  8.5000, 15.0000])

### using eye

In [11]:
'''
torch.eye(dim)
make a tonsor of a identity matrix for the given dim
'''
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### using full

In [12]:
'''
torch.full((shape),value)
create a tensor of given size and assion the given value to it.
'''
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [13]:
# creating a tensor 
tensor = torch.tensor([[1,2,3],[4,5,6],])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

### check the shape of the tensor

In [14]:
'''
tensor.shape
return the shape of the tensor
'''
tensor.shape

torch.Size([2, 3])

### making the tensor of same shape

In [15]:
'''
torch.empty_like(other_tensor)
make a empty tensor of same shape as given tensor
'''
torch.empty_like(tensor)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
'''
torch.zeros_like(other_tensor)
return a zero tensor of same shape as given tensor
'''
torch.zeros_like(tensor)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
'''
torch.ones_like(other_tensor)
return a one tensor of same shape as given tensor
'''
torch.ones_like(tensor)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
'''
torch.rand_like(other_tensor,dtype=torch.float32)
return a tensor with random values between 0 to 1 of same shape as given tensor
dtype=torch.float32 is used to change the data type of old tensor for more see below....(tensor data type)
'''
torch.rand_like(tensor,dtype=torch.float32)

tensor([[0.7861, 0.0566, 0.7842],
        [0.1480, 0.0388, 0.1037]])

# Tensor data type

<img src="local images/data types in pytorch.png"/>

### Finding the datatype

In [19]:
tensor.dtype

torch.int64

### assign datatype

In [20]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

### useing to()

In [21]:
tensor.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

## Scalar Operations

_working with single tensor_

In [44]:
x = torch.tensor([[-1.9,2.8,-3.2],[4.4,-5.0,6.001]])
x

tensor([[-1.9000,  2.8000, -3.2000],
        [ 4.4000, -5.0000,  6.0010]])

### addition

In [45]:
'''
addition of 10 in every item of a tensor
'''
x+10

tensor([[ 8.1000, 12.8000,  6.8000],
        [14.4000,  5.0000, 16.0010]])

### substraction

In [46]:
'''
substraction of 2 in every item of a tensor
'''
x-2

tensor([[-3.9000,  0.8000, -5.2000],
        [ 2.4000, -7.0000,  4.0010]])

### multiplication

In [47]:
'''
multiplication of 2 in every item of a tensor
'''
x*2

tensor([[ -3.8000,   5.6000,  -6.4000],
        [  8.8000, -10.0000,  12.0020]])

### division

In [48]:
'''
division of 2 in every item of a tensor
'''
x/2

tensor([[-0.9500,  1.4000, -1.6000],
        [ 2.2000, -2.5000,  3.0005]])

### int division

In [49]:
'''
int division of 2 in every item of a tensor
'''
x//2

tensor([[-1.,  1., -2.],
        [ 2., -3.,  3.]])

### mod

In [50]:
'''
mod of 2 in every item of a tensor
'''
x%2

tensor([[1.0000e-01, 8.0000e-01, 8.0000e-01],
        [4.0000e-01, 1.0000e+00, 9.9993e-04]])

### power

In [51]:
'''
power of 2 in every item of a tensor
'''
x**2

tensor([[ 3.6100,  7.8400, 10.2400],
        [19.3600, 25.0000, 36.0120]])

### absolute

In [54]:
'''
abs removes the negative sign and return posative number
'''
torch.abs(x)

tensor([[1.9000, 2.8000, 3.2000],
        [4.4000, 5.0000, 6.0010]])

### negative

In [55]:
'''
neg reverse the sign means posative become's negative and negative becomes posative
'''
torch.neg(x)

tensor([[ 1.9000, -2.8000,  3.2000],
        [-4.4000,  5.0000, -6.0010]])

### round

In [56]:
'''
round the numbers of the tensor
'''
torch.round(x)

tensor([[-2.,  3., -3.],
        [ 4., -5.,  6.]])

### ceil

In [57]:
'''
rounding the numbers but the element will always converted to there next rounding number
'''
torch.ceil(x)

tensor([[-1.,  3., -3.],
        [ 5., -5.,  7.]])

### floor

In [58]:
'''
rounding the numbers but the element will always converted to there previous rounding number
'''
torch.floor(x)

tensor([[-2.,  2., -4.],
        [ 4., -5.,  6.]])

### clamp

In [59]:
'''
clamp allow us to pic a range of number from which if a number falls outside the range
they are converted into eather minimum or maximum number of that range according to there posations
'''
torch.clamp(x,min=2,max=3)

tensor([[2.0000, 2.8000, 2.0000],
        [3.0000, 2.0000, 3.0000]])

## Element wise operations

_working with multiple tensor_

In [36]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7759, 0.3159, 0.1600],
        [0.5838, 0.4831, 0.1120]])
tensor([[0.7900, 0.1813, 0.1004],
        [0.1655, 0.5094, 0.5793]])


### addition

In [38]:
'''
addition of two tensors of same size metrics
'''
a+b

tensor([[1.5659, 0.4971, 0.2604],
        [0.7493, 0.9925, 0.6913]])

### substraction

In [39]:
'''
substraction of two tensors of same size metrics
'''
a-b

tensor([[-0.0141,  0.1346,  0.0595],
        [ 0.4183, -0.0263, -0.4672]])

### multiplication

In [40]:
'''
multiplication of two tensors of same size metrics
'''
a*b

tensor([[0.6130, 0.0573, 0.0161],
        [0.0966, 0.2461, 0.0649]])

### division

In [41]:
'''
division of two tensors of same size metrics
'''
a/b

tensor([[0.9822, 1.7423, 1.5928],
        [3.5274, 0.9484, 0.1934]])

### mod

In [42]:
'''
mod of two tensors of same size metrics
'''
a%b

tensor([[0.7759, 0.1346, 0.0595],
        [0.0873, 0.4831, 0.1120]])

### power

In [43]:
'''
power of two tensors of same size metrics
'''
a**b

tensor([[0.8184, 0.8115, 0.8319],
        [0.9148, 0.6903, 0.2814]])

## rediction operation

_reducing all the elements of the tenson into a single tensor_

In [60]:
c=torch.randint(size=(2,3), low=0, high=20)
c

tensor([[ 7, 16, 12],
        [ 9, 13,  3]])

### sum

In [61]:
# all elements sum
torch.sum(c)

tensor(60)

In [63]:
# sum by column
torch.sum(c, dim=0)

tensor([16, 29, 15])

In [64]:
# sum by rows
torch.sum(c, dim=1)

tensor([35, 25])

### mean

In [66]:
# mean od all elements
torch.mean(c,dtype=torch.float32)

tensor(10.)

In [67]:
# mean along columns
torch.mean(c, dtype=torch.float32, dim=0)

tensor([ 8.0000, 14.5000,  7.5000])

In [68]:
# mean along rows
torch.mean(c, dtype=torch.float32, dim=1)

tensor([11.6667,  8.3333])

### median

In [69]:
torch.median(c)

tensor(9)

### max and min

In [70]:
torch.max(c)

tensor(16)

In [71]:
torch.min(c)

tensor(3)

### product

In [72]:
torch.prod(c)

tensor(471744)

### standard deviation

In [74]:
torch.std(c.to(torch.float16))

tensor(4.6484, dtype=torch.float16)

### variance

In [75]:
torch.var(c.to(torch.float16))

tensor(21.5938, dtype=torch.float16)

### argmax

In [76]:
'''
return the index/posation of the largest number
'''
torch.argmax(c)

tensor(1)

### argmin

In [77]:
'''
return the index/posation of the smallest number
'''
torch.argmin(c)

tensor(5)

In [81]:
'''
return index of all non zero elements
'''
torch.argwhere(c)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2]])

## Metrix operations

In [83]:
i = torch.randint(size=(2,3),low=0, high=10)
j = torch.randint(size=(3,5),low=0, high=10)

print(i)
print(j)

tensor([[1, 7, 6],
        [8, 7, 7]])
tensor([[6, 4, 1, 8, 4],
        [2, 7, 4, 8, 0],
        [3, 4, 2, 2, 4]])


### matrix multiplaction

In [86]:
torch.matmul(i,j)

tensor([[ 38,  77,  41,  76,  28],
        [ 83, 109,  50, 134,  60]])

### dot product

In [87]:
v1=torch.tensor([1,2])
v2=torch.tensor([3,4])

torch.dot(v1,v2)

tensor(11)

### transpose

In [88]:
i

tensor([[1, 7, 6],
        [8, 7, 7]])

In [91]:
'''
torch.transpose(matrix, dim1 of matrix, dim1 of matrix)
dim1 will we swap with dim2
0=column
1=row
'''
torch.transpose(i,0,1)

tensor([[1, 8],
        [7, 7],
        [6, 7]])

### determinent

In [96]:
k=torch.randint(size=(3,3),low=0, high=10,dtype=torch.float32)
print(k)

tensor([[1., 5., 9.],
        [5., 7., 6.],
        [9., 5., 7.]])


In [97]:
torch.det(k)

tensor(-228.0000)

### Inverse

In [98]:
torch.inverse(k)

tensor([[-0.0833, -0.0439,  0.1447],
        [-0.0833,  0.3246, -0.1711],
        [ 0.1667, -0.1754,  0.0789]])

## Comparision operations 

In [105]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 4, 3],
        [7, 4, 8]])
tensor([[1, 9, 0],
        [3, 9, 1]])


### greater then

In [106]:
i<j

tensor([[False,  True, False],
        [False,  True, False]])

### less then

In [107]:
i>j

tensor([[False, False,  True],
        [ True, False,  True]])

### equale to

In [108]:
i==j

tensor([[ True, False, False],
        [False, False, False]])

### not equale to

In [109]:
i!=j

tensor([[False,  True,  True],
        [ True,  True,  True]])

### greater then equale to

In [110]:
i>=j

tensor([[ True, False,  True],
        [ True, False,  True]])

## special Function

In [111]:
z = torch.randint(size=(2,3), low=0, high=10)
z

tensor([[6, 1, 9],
        [0, 6, 6]])

### log

In [112]:
torch.log(z)

tensor([[1.7918, 0.0000, 2.1972],
        [  -inf, 1.7918, 1.7918]])

### exp

In [113]:
torch.exp(z)

tensor([[4.0343e+02, 2.7183e+00, 8.1031e+03],
        [1.0000e+00, 4.0343e+02, 4.0343e+02]])

### sqrt

In [114]:
torch.sqrt(z)

tensor([[2.4495, 1.0000, 3.0000],
        [0.0000, 2.4495, 2.4495]])

### sigmoid

In [115]:
torch.sigmoid(z)

tensor([[0.9975, 0.7311, 0.9999],
        [0.5000, 0.9975, 0.9975]])

### softmax

In [116]:
torch.softmax(z,dim=0,dtype=torch.float32)

tensor([[0.9975, 0.0067, 0.9526],
        [0.0025, 0.9933, 0.0474]])

### relu

In [117]:
torch.relu(z)

tensor([[6, 1, 9],
        [0, 6, 6]])

# Inplace Operations

In [119]:
'''
if you perform an operation between 2 metrix and want the result to be saved in one of them
to save spae or for some uther resion use operations followed by a "_"  sign.

example
t.sum_()
t.mul_()
t.relu_()
'''
print("i= ",i)
print("j =",j)

j.add_(i)
print("j =",j)

i=  tensor([[1, 4, 3],
        [7, 4, 8]])
j = tensor([[ 2, 13,  3],
        [10, 13,  9]])
j = tensor([[ 3, 17,  6],
        [17, 17, 17]])


# Copy a tensor

In [120]:
a=torch.rand(2,3)
a

tensor([[0.2879, 0.0578, 0.0138],
        [0.8276, 0.1783, 0.7180]])

In [121]:
b = a.clone()
b

tensor([[0.2879, 0.0578, 0.0138],
        [0.8276, 0.1783, 0.7180]])

In [124]:
# memory address of a and b.
print("address of a =",id(a))
print("address of b =",id(b))

address of a = 2225516591680
address of b = 2225507227632


# Tensor Operations in GPU

In [125]:
torch.cuda.is_available()

True

In [126]:
device = torch.device("cuda")

## making new tensors in GPU

In [127]:
torch.rand((2,3),device=device)

tensor([[0.9932, 0.3696, 0.2102],
        [0.9423, 0.9890, 0.2813]], device='cuda:0')

## moving an existing tensor to GPU

In [129]:
# on CPU
k

tensor([[1., 5., 9.],
        [5., 7., 6.],
        [9., 5., 7.]])

In [130]:
k.to(device)

tensor([[1., 5., 9.],
        [5., 7., 6.],
        [9., 5., 7.]], device='cuda:0')

**now all the operation in done in gpu**

## compareing GPU vs CPU

In [3]:
import time

processes_start = time.time()
size=15000
# creating a matrix
tensor_1 = torch.rand(size,size)
tensor_2 = torch.rand(size,size)

# measure cpu time for matmul
start_time = time.time()
result=torch.matmul(tensor_1,tensor_2)
cpu_time = time.time()-start_time
print("cpu done!")
print(f"CPU time = {cpu_time:.4f} second")

# moving matrix to gpu
tensor_1 = tensor_1.to("cuda")
tensor_2 = tensor_2.to("cuda")

# measure the gpu time for matmul
start_time = time.time()
result=torch.matmul(tensor_1,tensor_2)
torch.cuda.synchronize() # ensure all the gpu operations are completed
gpu_time = time.time()-start_time
print("gpu done!")
print(f"GPU time = {gpu_time:.4f} second")

print("-"*20)
print("total time =",time.time()-processes_start)

cpu done!
CPU time = 18.8318 second
gpu done!
GPU time = 4.4497 second
--------------------
total time = 27.88403058052063


# Reshaping tensors

In [4]:
x=torch.ones(4,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## reshape

In [6]:
x.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

## flatten

In [7]:
x.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## permute

In [8]:
a=torch.rand(2,3,4)
a

tensor([[[0.8194, 0.3515, 0.6677, 0.8682],
         [0.9311, 0.7116, 0.4182, 0.0542],
         [0.8300, 0.9667, 0.9131, 0.0099]],

        [[0.7666, 0.0188, 0.1156, 0.9737],
         [0.2426, 0.3561, 0.1918, 0.6857],
         [0.7446, 0.1717, 0.4650, 0.7105]]])

In [10]:
'''
it means our dim 2->first place, 0->secondplace, 1->lastplace
so.
    if (2,3,4) index is (0,1,2)
    after permute index =(2,0,1)
    hence shape=(4,2,3)
'''
a.permute(2,0,1)

tensor([[[0.8194, 0.9311, 0.8300],
         [0.7666, 0.2426, 0.7446]],

        [[0.3515, 0.7116, 0.9667],
         [0.0188, 0.3561, 0.1717]],

        [[0.6677, 0.4182, 0.9131],
         [0.1156, 0.1918, 0.4650]],

        [[0.8682, 0.0542, 0.0099],
         [0.9737, 0.6857, 0.7105]]])

## unsqueeze

In [11]:
'''
add a dim in a matrix
image.unsqueeze(posation to add a dim)
'''
image = torch.rand(226,226,3)
image.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

## squeeze

In [12]:
tensor = torch.rand(1,20)
tensor.squeeze(0).shape

torch.Size([20])

# numpy and pytorch

In [15]:
import torch
import numpy as np

## pytorch tensor to numpy array

In [13]:
# creating a pytorch tensor
py_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
py_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
np_array = py_tensor.numpy()
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## numpy array pytorch tensor

In [16]:
num_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
num_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
pyto_tensor=torch.from_numpy(num_array)
pyto_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])