# Autograd

Autograd is a core component of pytorch that provides automatic differentation operations for operations.
it enables gradient computations, which is essential for traning machine learning models using optimization algos like gradient descent

# Basic Steps to Use Autograd

if x = 3 and y=x**2  
so:  
y=9,  
**finding- $\frac{dy}{dx}$ = 2x = 6**

In [8]:
import torch

In [9]:
'''the tensor should be in floating numbers'''
x=torch.tensor([3.0],requires_grad=True)
x

tensor([3.], requires_grad=True)

In [10]:
# make a function
y=x**2
y

tensor([9.], grad_fn=<PowBackward0>)

# backward tracking and finding gradient

In [11]:
# only for scaler inputs
y.backward()

In [12]:
x.grad

tensor([6.])

# removing the pre save gradient

In [14]:
x.grad.zero_()

tensor([0.])

# disable gradient tracking

## requires_grad_(False)

In [17]:
x=torch.tensor([3.0],requires_grad=True)
y=x**2
y

tensor([9.], grad_fn=<PowBackward0>)

In [20]:
x.requires_grad_(False)
y=x**2
y

tensor([9.])

## detach()

In [21]:
x=torch.tensor([3.0],requires_grad=True)
y=x**2
y

tensor([9.], grad_fn=<PowBackward0>)

In [22]:
z=x.detach()
y=z**2
y

tensor([9.])

## torch.no_grad()

In [23]:
x=torch.tensor([3.0],requires_grad=True)
y=x**2
y

tensor([9.], grad_fn=<PowBackward0>)

In [24]:
with torch.no_grad():
    y=x**2
y

tensor([9.])