# what is a pytorch nn module?

the torch.nn module in pytorch is a core library that provide a large array of classes and functions designe to help developers build neural network effectively and efficently. it offer pre build layers, loss functions, activation functions, and other utilities.

**key components if nn module**
1. Modules (Layers):
   * nn.modules:
   * common layers:
2. Activation function
3. loss functions
4. container module
   * nn.Sequential
5. Regularization and Dropout

## Improvements

1. Building a neural network using a nn module
2. using built in activation module
3. using built in loss function
4. using built in optimizer

# Building a model

In [1]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__() # calling the constructor of the parent class
        self. linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, features):
        out = self.linear(features)
        out=self.sigmoid(out)
        return out

In [4]:
# creation a temp data
features = torch.rand(10,5)

# creating model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4848],
        [0.5740],
        [0.4619],
        [0.5146],
        [0.5541],
        [0.4852],
        [0.5063],
        [0.4332],
        [0.4358],
        [0.5277]], grad_fn=<SigmoidBackward0>)

In [9]:
# display the weights and bias
model.linear.weight,model.linear.bias

(Parameter containing:
 tensor([[-0.4164, -0.3763,  0.3343, -0.4209,  0.2766]], requires_grad=True),
 Parameter containing:
 tensor([0.3393], requires_grad=True))

In [ ]:
! pip install torchinfo

In [13]:
# visualize the model
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Making NN with hiddan layers

<img src="local images/5_3_nn.png">

In [16]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__() # calling the constructor of the parent class
        self. linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self. linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear1(features)
        out=self.relu(out)
        out = self.linear2(out)
        out=self.sigmoid(out)
        
        return out

In [17]:
# creation a temp data
features = torch.rand(10,5)

# creating model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4358],
        [0.4321],
        [0.4171],
        [0.4460],
        [0.4313],
        [0.4483],
        [0.4485],
        [0.4133],
        [0.4354],
        [0.4332]], grad_fn=<SigmoidBackward0>)

In [19]:
# display the weights and bias
model.linear1.weight,model.linear1.bias

(Parameter containing:
 tensor([[ 0.3972, -0.0026,  0.1789, -0.2397, -0.0190],
         [ 0.0248,  0.4440,  0.4408,  0.4131, -0.0794],
         [-0.3820,  0.0901,  0.1096,  0.0367, -0.2818]], requires_grad=True),
 Parameter containing:
 tensor([-0.3951,  0.3575, -0.0143], requires_grad=True))

In [20]:
# display the weights and bias
model.linear2.weight,model.linear2.bias

(Parameter containing:
 tensor([[-0.3387, -0.2495,  0.3033]], requires_grad=True),
 Parameter containing:
 tensor([-0.0293], requires_grad=True))

In [21]:
# visualize the model
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using sequential container

In [22]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        out = self.network(features)
        
        return out

In [23]:
# creation a temp data
features = torch.rand(10,5)

# creating model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.6078],
        [0.6577],
        [0.6272],
        [0.6477],
        [0.6051],
        [0.6625],
        [0.6027],
        [0.6071],
        [0.6206],
        [0.6594]], grad_fn=<SigmoidBackward0>)

# Improveing our traning pipeline

In [24]:
import numpy as np
import pandas as pd 
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

## 1. Load the dataset

In [25]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [26]:
df.shape

(569, 33)

In [27]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## 2. Basic preprocessing

In [28]:
xtrain, xtest, ytrain, ytest = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)
print(f"size of xtrain = {xtrain.shape}")
print(f"size of xtest = {xtest.shape}")
print(f"size of ytrain = {ytrain.shape}")
print(f"size of ytest = {ytest.shape}")

size of xtrain = (455, 30)
size of xtest = (114, 30)
size of ytrain = (455,)
size of ytest = (114,)


In [29]:
scaler = StandardScaler()
x_train = scaler.fit_transform(xtrain)
x_test = scaler.transform(xtest)
x_train

array([[-0.15085962, -0.69326458, -0.20710522, ..., -0.44815201,
        -0.93042378, -0.19311885],
       [-0.65312476, -0.44018959, -0.68264603, ..., -0.36328574,
         0.34585591, -0.77355307],
       [-1.04876379, -0.89210922, -1.0461271 , ..., -1.07959387,
        -0.47569631, -0.05399709],
       ...,
       [-0.3444702 , -0.76557172, -0.37295364, ..., -0.14575846,
         0.81748775,  0.69577796],
       [ 0.09886998, -0.01538513,  0.07976773, ..., -0.29373828,
        -0.71911919, -0.51355503],
       [ 0.44119594, -0.04250031,  0.60339236, ...,  1.50714247,
         2.27971548,  1.21805473]], shape=(455, 30))

In [30]:
encoder=LabelEncoder()
y_train = encoder.fit_transform(ytrain)
y_test = encoder.transform(ytest)
y_train

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,

### Numpy array to torch tensor

In [38]:
xtrain_tensor = torch.from_numpy(x_train).float()
xtest_tensor = torch.from_numpy(x_test).float()
ytrain_tensor = torch.from_numpy(y_train).float()
ytest_tensor = torch.from_numpy(y_test).float()
xtrain_tensor.shape

torch.Size([455, 30])

## 3. Training process

In [39]:
class MySampleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        z = self.linear(x)
        y_pred = self.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

        # calculate loss
        loss = -(y+torch.log(y_pred)+(1-y)).mean()
        return loss

In [45]:
learning_rate=0.5
epochs = 20

In [46]:
#  create model object
model = MySampleNN(xtrain_tensor.shape[1])

# defining loop
for epoch in range(epochs):
    # forword pass
    y_pred = model(xtrain_tensor)

    # calculating loss
    loss=model.loss_function(y_pred,ytrain_tensor)
    print(f"epoch:{epoch+1}, Loss:{loss}")

    # backword pass
    loss.backward()

    # peramaters update
    with torch.no_grad():
        model.linear.weight -= learning_rate*model.linear.weight.grad
        model.linear.bias -= learning_rate*model.linear.bias.grad

        # zero gradient
        model.linear.weight.grad.zero_()
        model.linear.bias.grad.zero_()

epoch:1, Loss:-0.3590449392795563
epoch:2, Loss:-0.471561074256897
epoch:3, Loss:-0.5536534786224365
epoch:4, Loss:-0.6161279678344727
epoch:5, Loss:-0.6649046540260315
epoch:6, Loss:-0.7037864327430725
epoch:7, Loss:-0.735346794128418
epoch:8, Loss:-0.7613595724105835
epoch:9, Loss:-0.7830893993377686
epoch:10, Loss:-0.8014591336250305
epoch:11, Loss:-0.8171553015708923
epoch:12, Loss:-0.830696165561676
epoch:13, Loss:-0.8424792289733887
epoch:14, Loss:-0.8528125882148743
epoch:15, Loss:-0.8619389533996582
epoch:16, Loss:-0.870050847530365
epoch:17, Loss:-0.8773034811019897
epoch:18, Loss:-0.8838221430778503
epoch:19, Loss:-0.889710009098053
epoch:20, Loss:-0.895051896572113


# BUILT-IN loss function

In [47]:
class MySampleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        z = self.linear(x)
        y_pred = self.sigmoid(z)
        return y_pred

In [48]:
loss_function = nn.BCELoss()

In [49]:
learning_rate=0.5
epochs = 20

In [52]:
#  create model object
model = MySampleNN(xtrain_tensor.shape[1])

# defining loop
for epoch in range(epochs):
    # forword pass
    y_pred = model(xtrain_tensor)

    # calculating loss
    loss=loss_function(y_pred,ytrain_tensor.view(-1,1)) #match the shape
    print(f"epoch:{epoch+1}, Loss:{loss}")

    # backword pass
    loss.backward()

    # peramaters update
    with torch.no_grad():
        model.linear.weight -= learning_rate*model.linear.weight.grad
        model.linear.bias -= learning_rate*model.linear.bias.grad

        # zero gradient
        model.linear.weight.grad.zero_()
        model.linear.bias.grad.zero_()

epoch:1, Loss:0.6007298827171326
epoch:2, Loss:0.22492170333862305
epoch:3, Loss:0.19277004897594452
epoch:4, Loss:0.17321722209453583
epoch:5, Loss:0.15976350009441376
epoch:6, Loss:0.14980874955654144
epoch:7, Loss:0.14207230508327484
epoch:8, Loss:0.1358422040939331
epoch:9, Loss:0.13068820536136627
epoch:10, Loss:0.1263335794210434
epoch:11, Loss:0.12259157747030258
epoch:12, Loss:0.11933105438947678
epoch:13, Loss:0.1164570078253746
epoch:14, Loss:0.11389871686697006
epoch:15, Loss:0.1116023063659668
epoch:16, Loss:0.1095258966088295
epoch:17, Loss:0.10763649642467499
epoch:18, Loss:0.1059076339006424
epoch:19, Loss:0.10431776940822601
epoch:20, Loss:0.10284925252199173


In [53]:
 with torch.no_grad():
    y_pred = model.forward(xtest_tensor)
    y_pred = (y_pred>0.5).float()
    accuracy = (y_pred == ytest_tensor).float().mean()
    print(f"accuracy:{accuracy.item()}")

accuracy:0.5467836260795593


# useing BUILT-IN optimizer

In [54]:
class MySampleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        z = self.linear(x)
        y_pred = self.sigmoid(z)
        return y_pred

In [55]:
learning_rate=0.5
epochs = 20

In [56]:
loss_function = nn.BCELoss()

In [57]:
#  create model object
model = MySampleNN(xtrain_tensor.shape[1])

# defining optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# defining loop
for epoch in range(epochs):
    
    # forword pass
    y_pred = model(xtrain_tensor)

    # calculating loss
    loss=loss_function(y_pred,ytrain_tensor.view(-1,1)) #match the shape
    print(f"epoch:{epoch+1}, Loss:{loss}")

    # zero gradient
    optimizer.zero_grad()
    
    # backword pass
    loss.backward()

    # peramaters update
    optimizer.step()

epoch:1, Loss:0.7379255294799805
epoch:2, Loss:0.23079770803451538
epoch:3, Loss:0.19648995995521545
epoch:4, Loss:0.1747017353773117
epoch:5, Loss:0.15975020825862885
epoch:6, Loss:0.14890380203723907
epoch:7, Loss:0.14064620435237885
epoch:8, Loss:0.1341084986925125
epoch:9, Loss:0.12877348065376282
epoch:10, Loss:0.12431650608778
epoch:11, Loss:0.12052300572395325
epoch:12, Loss:0.1172448992729187
epoch:13, Loss:0.11437631398439407
epoch:14, Loss:0.11183930933475494
epoch:15, Loss:0.10957515984773636
epoch:16, Loss:0.10753859579563141
epoch:17, Loss:0.10569413006305695
epoch:18, Loss:0.10401352494955063
epoch:19, Loss:0.10247396677732468
epoch:20, Loss:0.10105687379837036


In [58]:
 with torch.no_grad():
    y_pred = model.forward(xtest_tensor)
    y_pred = (y_pred>0.5).float()
    accuracy = (y_pred == ytest_tensor).float().mean()
    print(f"accuracy:{accuracy.item()}")

accuracy:0.5393967628479004
