# Datasets and dataloaders

_**dataset and dataLoader** are core abstraction in pytorch that decouple how you define your data from how you efficiently iterate over it_

**Problums it solves**
1. No standard interface for data
2. No easy way to apply transformations
3. shuffling and samplings
4. Batch management and parallelization

## Components

### Dataset Class
_The data set class is essentially a blueprint. when you create a custom dataset, you will decide how the data is loaded and returned._

it defines:  
  * ```__init__() ``` Which tells how the data shpuld be loaded **_(from pd.readcsv or by folder)_**
  * ```__len__()``` Which returns the total number of samples
  * ```__getitem__(index)``` Which return the data (and labels) at the given index

### DataLoader
1. At the start of each epoch, the DataLoader (if shuffle=True) shuffles indices (useing a sampler).
2. it divides the index into chunk of batch_size
3. for each index in the chunk, data samples are fatched from the dataset object
4. The samples are then collected and combined into a batch (using collate_fn)
5. The batch is returned to the main traning loop

# Dataset Loading and Preprocessing

In [11]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.drop(columns=["id","Unnamed: 32"],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [13]:
df.shape

(569, 31)

In [30]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

scaler = StandardScaler()
x = scaler.fit_transform(x)
x

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]], shape=(569, 30))

In [32]:
encoder=LabelEncoder()
y = encoder.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [33]:
x.shape

(569, 30)

In [34]:
y.shape

(569,)

# Working with Dataloader and Custom Dataset

## Converting array to tensor

In [35]:
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [42]:
x.shape, x #x and y is a pytorch tensor

(torch.Size([569, 30]),
 tensor([[ 1.0971, -2.0733,  1.2699,  ...,  2.2961,  2.7506,  1.9370],
         [ 1.8298, -0.3536,  1.6860,  ...,  1.0871, -0.2439,  0.2812],
         [ 1.5799,  0.4562,  1.5665,  ...,  1.9550,  1.1523,  0.2014],
         ...,
         [ 0.7023,  2.0456,  0.6727,  ...,  0.4141, -1.1045, -0.3184],
         [ 1.8383,  2.3365,  1.9825,  ...,  2.2900,  1.9191,  2.2196],
         [-1.8084,  1.2218, -1.8144,  ..., -1.7451, -0.0481, -0.7512]]))

## Creating a custom Dataset

In [41]:
from torch.utils.data import Dataset, DataLoader

In [43]:
class CustomDataset(Dataset):
    
    def __init__(self,features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [44]:
dataset = CustomDataset(x,y)

## Working in DataLoader

_format :_ dataloader = **DataLoader(_dataset object_, _batch size_, _shuffle=True/False_)**

In [59]:
dataloader = DataLoader(dataset, batch_size=50, shuffle=True)
dataloader

In [67]:
i=0
for batch_features, batch_labels in dataloader:
    if i==4:break
    print(batch_features)
    print(batch_labels)
    print("-"*50)
    i+=1

tensor([[-0.8172, -1.0494, -0.8481,  ..., -1.4912, -0.1387, -0.5412],
        [-0.9052, -0.1628, -0.8888,  ..., -0.5441, -1.0512, -0.3672],
        [-0.7149, -0.7609, -0.6800,  ..., -0.0625, -0.1840, -0.5362],
        ...,
        [-0.9848, -0.9633, -1.0083,  ..., -1.7451, -0.3086, -1.2361],
        [-0.3826, -0.6515, -0.4366,  ..., -0.8494, -0.8376, -1.0998],
        [ 1.5515, -0.2652,  1.5953,  ...,  1.6764,  1.2008,  0.4591]])
tensor([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 1])
--------------------------------------------------
tensor([[-0.6042,  2.0805, -0.6261,  ..., -0.6615, -0.7341, -0.1112],
        [-1.2466, -1.7033, -1.2657,  ..., -1.7451,  0.3304, -0.1350],
        [-0.4508, -0.6911, -0.4415,  ..., -0.4644,  0.4113, -0.4747],
        ...,
        [ 2.6648,  1.1590,  2.6004,  ...,  1.4358, -0.4979, -0.3639],
        [-0.7973,  1.8129, -0.8324,  ..., -1.42

# Components of the data loading pipeline

## Data Transformation

The data transformation is done inside the custom dataset class  
```python
class CustomDataset(Dataset):
    
    def __init__(self,features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        '''
        all the transformations are done here before return statement
        '''
        return self.features[index], self.labels[index]
```

## Samplers

### Type of Samplers

1. SequentialSampler
2. RandomSampler
3. CustomSampler

## Collate_fn

* The Collate_fn in pytorch is a function that specifies how to combine a list of samples from a dataset into a list of sample from the dataset into a single batch
* By default, the dataLoader uses a simple batch collection mechanisum, but collate_fn allow you to customize that how the data should be processed and batched

## dataLoader Components

|s.no|components|Working|
|----|----------|-------|
|1|dataset (mendatory)|1. dataset from which the dataLoader will pull data|
|||2. Must be sub class of torch.utils.data.Dataset that implements ```__getitem__``` and ```__len__```|
||||
|2|batch_size|1. How many samples per batch to load|
|||2. default is 1.|
|||3. Larger batch size can speed up traning on GPU but required more memory|
||||
|3|shuffle|1 how the shuffle the dataset|
||||
|4|num_workes|1. The number of worker processes used to load data in parallel|
|||2. setting num_workers>0 can speedup the data loading by useing multiple CPU cores, especially if I/O is a bottleneck|
||||
|5|pin_memory|1. if True the dataloader will copy tensors into pinned (page-locked) memory before returning them.|
|||2. this can improve transfur speed over all traning time|
||||
|6|drop_last|1. if True, the dataloader will drop the last batch if the last batch is not divided by the batch size|
|||2. usefull when exect batch size is required|
||||
|7|collate_fn| a collabe that process a list of sample into a batch|
|||custom collate_fn can handle veriable length sequence, perform custom batching, logic and handle complex data stracture|
||||
|8|sampler|1. sampler define the strategy for drowing samples|
|||2. batch_sampler workes at batch level, controlling how batches are formed|

# Improving our code for Mini-batch gradient descent (MBGD)

In [68]:
import numpy as np
import pandas as pd 
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

## 1. Load the dataset

In [69]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [70]:
df.shape

(569, 33)

In [71]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## 2. Basic preprocessing

In [72]:
xtrain, xtest, ytrain, ytest = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)
print(f"size of xtrain = {xtrain.shape}")
print(f"size of xtest = {xtest.shape}")
print(f"size of ytrain = {ytrain.shape}")
print(f"size of ytest = {ytest.shape}")

size of xtrain = (455, 30)
size of xtest = (114, 30)
size of ytrain = (455,)
size of ytest = (114,)


Scaling

In [73]:
scaler = StandardScaler()
x_train = scaler.fit_transform(xtrain)
x_test = scaler.transform(xtest)
x_train

array([[ 0.95981435,  4.70220918,  0.8952502 , ...,  1.38525468,
        -0.08463945,  0.05430031],
       [ 0.45152639,  0.26590046,  0.38404019, ...,  0.59038292,
         0.85328096,  0.1277591 ],
       [-0.82496951, -1.35240509, -0.79760918, ..., -0.43901385,
        -1.29076655, -0.87726599],
       ...,
       [-1.14553749, -1.00395491, -1.15168497, ..., -1.35228365,
         1.04600434, -0.20470995],
       [-0.78164952, -0.88468672, -0.79509503, ..., -0.45945341,
        -0.36890642, -0.88760463],
       [-0.68634552,  0.56757881, -0.72553695, ..., -1.18028854,
        -0.75917125, -0.99752075]], shape=(455, 30))

Label Encoding

In [74]:
encoder=LabelEncoder()
y_train = encoder.fit_transform(ytrain)
y_test = encoder.transform(ytest)
y_train

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,

## 3. Numpy array to torch tensor

In [75]:
xtrain_tensor = torch.from_numpy(x_train).float()
xtest_tensor = torch.from_numpy(x_test).float()
ytrain_tensor = torch.from_numpy(y_train).float()
ytest_tensor = torch.from_numpy(y_test).float()
xtrain_tensor.shape

torch.Size([455, 30])

In [76]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [77]:
train_dataset = CustomDataset(xtrain_tensor, ytrain_tensor)
test_dataset = CustomDataset(xtest_tensor, ytest_tensor)

In [78]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

## 4. Define model

In [84]:
import torch.nn as nn

class MySampleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        z = self.linear(x)
        y_pred = self.sigmoid(z)
        return y_pred

## 5. Important peramaters

In [85]:
learning_rate = 0.5
epoch = 20

In [86]:
#  create model object
model = MySampleNN(xtrain_tensor.shape[1])

# define loss function
loss_function = nn.BCELoss()

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

## 6. Traning pipeline

In [89]:
# define loop
for epoch in range(epoch):
    batch_no=0
    for batch_features, batch_labels in train_loader:
        batch_no += 1
        # print(f" starting batch:{batch_no}", end='')

        # forword pass
        y_pred = model(batch_features)
        # print("..",end='')

        # calculate loss
        loss = loss_function(y_pred, batch_labels.view(-1,1))
        # print("..",end='')

        # clear gradient
        optimizer.zero_grad()
        # print("..",end='')

        # backword pass
        loss.backward()
        # print("..",end='')

        # peramaters update
        optimizer.step()
        # print("completed !")
        
    print(f"epoch:{epoch+1}, Loss:{loss.item()}")

epoch:1, Loss:0.06697898358106613
epoch:2, Loss:0.005849621258676052
epoch:3, Loss:0.026851404458284378
epoch:4, Loss:0.0021070712246000767
epoch:5, Loss:0.0011778130428865552
epoch:6, Loss:0.0034802102018147707
epoch:7, Loss:0.005072867032140493
epoch:8, Loss:0.06353352963924408
epoch:9, Loss:0.007249873131513596
epoch:10, Loss:0.11506259441375732
epoch:11, Loss:0.053134653717279434
epoch:12, Loss:0.015455037355422974
epoch:13, Loss:0.0035428237169981003
epoch:14, Loss:0.0011248314986005425
epoch:15, Loss:0.004652294795960188
epoch:16, Loss:0.003202262567356229
epoch:17, Loss:0.05506148561835289
epoch:18, Loss:0.035806674510240555


In [90]:
# Model evaluation using test loader
model.eval() #set the model to eval mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # forword pass
        y_pred = model.forward(batch_features)
        y_pred = (y_pred>0.5).float()

        # accuracy of current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# calculate over all accuracy
total_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f"Accuracy: {total_accuracy:.4f}")

Accuracy: 0.9627
